/**
 * KaTeX Cheatsheet Data
 * Complete reference based on KaTeX supported functions (katex.org/docs/supported)
 * Table format with definition, math/comp-sci explanations, and usage
 */
export interface CheatsheetSymbol {
  name: string;
  code: string;
  definition: string;
  explanationMath: string;
  explanationCompSci: string;
  usage: string;
}

export interface CheatsheetCategory {
  title: string;
  symbols: CheatsheetSymbol[];
}

export const KATEX_CHEATSHEET: CheatsheetCategory[] = [
  {
    title: "Greek Uppercase",
    symbols: [
      { name: "Alpha", code: "\\Alpha", definition: "Greek A", explanationMath: "Often denotes angles or parameters", explanationCompSci: "Type variable; constant in algorithms", usage: "\\Alpha" },
      { name: "Beta", code: "\\Beta", definition: "Greek B", explanationMath: "Regression coefficients; angles", explanationCompSci: "Type parameter; false positive rate", usage: "\\Beta" },
      { name: "Gamma", code: "\\Gamma", definition: "Gamma function", explanationMath: "Generalizes factorial; Euler gamma", explanationCompSci: "Gamma distribution; type context", usage: "\\Gamma(n)" },
      { name: "Delta", code: "\\Delta", definition: "Delta", explanationMath: "Finite change; discriminant; Laplacian", explanationCompSci: "Delta encoding; version diff", usage: "\\Delta x" },
      { name: "Theta", code: "\\Theta", definition: "Theta", explanationMath: "Big Theta asymptotic bound", explanationCompSci: "Model parameters; tight complexity", usage: "\\Theta(n)" },
      { name: "Lambda", code: "\\Lambda", definition: "Lambda", explanationMath: "Eigenvalue; cosmological constant", explanationCompSci: "Lambda calculus; anonymous function", usage: "\\Lambda" },
      { name: "Xi", code: "\\Xi", definition: "Xi", explanationMath: "Random variable; slack variable", explanationCompSci: "State variable in systems", usage: "\\Xi" },
      { name: "Pi", code: "\\Pi", definition: "Pi", explanationMath: "Product notation; projection", explanationCompSci: "Product over sequence", usage: "\\Pi_{i=1}^{n}" },
      { name: "Sigma", code: "\\Sigma", definition: "Sigma", explanationMath: "Sum; covariance matrix", explanationCompSci: "Summation; alphabet", usage: "\\Sigma" },
      { name: "Phi", code: "\\Phi", definition: "Phi", explanationMath: "CDF; golden ratio conjugate", explanationCompSci: "Phase; feature map", usage: "\\Phi" },
      { name: "Psi", code: "\\Psi", definition: "Psi", explanationMath: "Wave function; digamma", explanationCompSci: "Neural network layer", usage: "\\Psi" },
      { name: "Omega", code: "\\Omega", definition: "Omega", explanationMath: "Big Omega asymptotic bound", explanationCompSci: "Lower bound complexity; sample space", usage: "\\Omega(n)" },
    ],
  },
  {
    title: "Greek Lowercase",
    symbols: [
      { name: "alpha", code: "\\alpha", definition: "Alpha", explanationMath: "Angles; significance level", explanationCompSci: "Learning rate; hyperparameter", usage: "\\alpha" },
      { name: "beta", code: "\\beta", definition: "Beta", explanationMath: "Regression coefficients", explanationCompSci: "Type parameter; decay rate", usage: "\\beta" },
      { name: "gamma", code: "\\gamma", definition: "Gamma", explanationMath: "Lorentz factor; Euler constant", explanationCompSci: "Discount factor in RL", usage: "\\gamma" },
      { name: "delta", code: "\\delta", definition: "Delta", explanationMath: "Infinitesimal change; Dirac delta", explanationCompSci: "Gradient; change variable", usage: "\\delta x" },
      { name: "epsilon", code: "\\epsilon", definition: "Epsilon", explanationMath: "Small positive; machine epsilon", explanationCompSci: "Tolerance; exploration rate", usage: "\\epsilon" },
      { name: "varepsilon", code: "\\varepsilon", definition: "Curly epsilon", explanationMath: "Variant epsilon", explanationCompSci: "Alternative epsilon glyph", usage: "\\varepsilon" },
      { name: "zeta", code: "\\zeta", definition: "Zeta", explanationMath: "Riemann zeta function", explanationCompSci: "Damping ratio", usage: "\\zeta" },
      { name: "eta", code: "\\eta", definition: "Eta", explanationMath: "Learning rate; efficiency", explanationCompSci: "Step size; decay", usage: "\\eta" },
      { name: "theta", code: "\\theta", definition: "Theta", explanationMath: "Angles; parameters", explanationCompSci: "Model parameters; weights", usage: "\\theta" },
      { name: "vartheta", code: "\\vartheta", definition: "Script theta", explanationMath: "Variant theta", explanationCompSci: "Alternative theta", usage: "\\vartheta" },
      { name: "iota", code: "\\iota", definition: "Iota", explanationMath: "Inclusion map", explanationCompSci: "Index; iterator", usage: "\\iota" },
      { name: "kappa", code: "\\kappa", definition: "Kappa", explanationMath: "Curvature; condition number", explanationCompSci: "Cohen kappa; rate", usage: "\\kappa" },
      { name: "lambda", code: "\\lambda", definition: "Lambda", explanationMath: "Eigenvalue; wavelength", explanationCompSci: "Lambda; decay constant", usage: "\\lambda" },
      { name: "mu", code: "\\mu", definition: "Mu", explanationMath: "Mean; measure", explanationCompSci: "Mean; micro-", usage: "\\mu" },
      { name: "nu", code: "\\nu", definition: "Nu", explanationMath: "Frequency; degrees of freedom", explanationCompSci: "Neutrino; variant", usage: "\\nu" },
      { name: "xi", code: "\\xi", definition: "Xi", explanationMath: "Random variable; state", explanationCompSci: "State; input", usage: "\\xi" },
      { name: "omicron", code: "\\omicron", definition: "Omicron", explanationMath: "Little o notation", explanationCompSci: "Small order", usage: "\\omicron" },
      { name: "pi", code: "\\pi", definition: "Pi", explanationMath: "Circle constant 3.14159", explanationCompSci: "Pi constant; projection", usage: "\\pi r^2" },
      { name: "varpi", code: "\\varpi", definition: "Curly pi", explanationMath: "Angular frequency variant", explanationCompSci: "Alternative pi", usage: "\\varpi" },
      { name: "rho", code: "\\rho", definition: "Rho", explanationMath: "Density; correlation", explanationCompSci: "Spearman rho; density", usage: "\\rho" },
      { name: "varrho", code: "\\varrho", definition: "Curly rho", explanationMath: "Variant rho", explanationCompSci: "Alternative rho", usage: "\\varrho" },
      { name: "sigma", code: "\\sigma", definition: "Sigma", explanationMath: "Standard deviation; sum", explanationCompSci: "Sigmoid; sigma algebra", usage: "\\sigma" },
      { name: "varsigma", code: "\\varsigma", definition: "Final sigma", explanationMath: "Word-final sigma", explanationCompSci: "Variant sigma", usage: "\\varsigma" },
      { name: "tau", code: "\\tau", definition: "Tau", explanationMath: "Time constant; torsion", explanationCompSci: "Time constant; type", usage: "\\tau" },
      { name: "upsilon", code: "\\upsilon", definition: "Upsilon", explanationMath: "Lambdabar in physics", explanationCompSci: "Symbol variant", usage: "\\upsilon" },
      { name: "phi", code: "\\phi", definition: "Phi", explanationMath: "Angle; golden ratio", explanationCompSci: "Activation; phase", usage: "\\phi" },
      { name: "varphi", code: "\\varphi", definition: "Curly phi", explanationMath: "Variant phi", explanationCompSci: "Alternative phi", usage: "\\varphi" },
      { name: "chi", code: "\\chi", definition: "Chi", explanationMath: "Chi-square; Euler characteristic", explanationCompSci: "Chi-square test", usage: "\\chi^2" },
      { name: "psi", code: "\\psi", definition: "Psi", explanationMath: "Wave function; digamma", explanationCompSci: "Wave function", usage: "\\psi" },
      { name: "omega", code: "\\omega", definition: "Omega", explanationMath: "Angular frequency", explanationCompSci: "Big omega; frequency", usage: "\\omega t" },
      { name: "digamma", code: "\\digamma", definition: "Digamma", explanationMath: "Digamma function", explanationCompSci: "Special function", usage: "\\digamma" },
    ],
  },
  {
    title: "Accents",
    symbols: [
      { name: "hat", code: "\\hat{x}", definition: "Hat accent", explanationMath: "Unit vector; estimate; Fourier", explanationCompSci: "Predicted value; estimate", usage: "\\hat{x}" },
      { name: "widehat", code: "\\widehat{xy}", definition: "Wide hat", explanationMath: "Hat over multiple chars", explanationCompSci: "Estimate over expression", usage: "\\widehat{ab}" },
      { name: "bar", code: "\\bar{x}", definition: "Bar accent", explanationMath: "Mean; conjugate; complement", explanationCompSci: "Average; negation", usage: "\\bar{x}" },
      { name: "overline", code: "\\overline{AB}", definition: "Overline", explanationMath: "Line over expression", explanationCompSci: "Complement; closure", usage: "\\overline{AB}" },
      { name: "tilde", code: "\\tilde{x}", definition: "Tilde", explanationMath: "Approximation; asymptotically", explanationCompSci: "Approximate; homotopy", usage: "\\tilde{x}" },
      { name: "widetilde", code: "\\widetilde{xy}", definition: "Wide tilde", explanationMath: "Tilde over multiple chars", explanationCompSci: "Approx over expression", usage: "\\widetilde{ab}" },
      { name: "vec", code: "\\vec{v}", definition: "Vector", explanationMath: "Vector quantity", explanationCompSci: "Vector; embedding", usage: "\\vec{v}" },
      { name: "dot", code: "\\dot{x}", definition: "Dot accent", explanationMath: "First derivative wrt time", explanationCompSci: "Time derivative", usage: "\\dot{x}" },
      { name: "ddot", code: "\\ddot{x}", definition: "Double dot", explanationMath: "Second derivative; acceleration", explanationCompSci: "Acceleration", usage: "\\ddot{x}" },
      { name: "dddot", code: "\\dddot{x}", definition: "Triple dot", explanationMath: "Third derivative", explanationCompSci: "Jerk derivative", usage: "\\dddot{x}" },
      { name: "ddddot", code: "\\ddddot{x}", definition: "Quadruple dot", explanationMath: "Fourth derivative", explanationCompSci: "Higher derivative", usage: "\\ddddot{x}" },
      { name: "acute", code: "\\acute{a}", definition: "Acute accent", explanationMath: "Accent mark", explanationCompSci: "Character accent", usage: "\\acute{a}" },
      { name: "grave", code: "\\grave{a}", definition: "Grave accent", explanationMath: "Accent mark", explanationCompSci: "Character accent", usage: "\\grave{a}" },
      { name: "breve", code: "\\breve{a}", definition: "Breve", explanationMath: "Short accent", explanationCompSci: "Character accent", usage: "\\breve{a}" },
      { name: "check", code: "\\check{a}", definition: "Caron", explanationMath: "Hacek accent", explanationCompSci: "Character accent", usage: "\\check{a}" },
      { name: "mathring", code: "\\mathring{a}", definition: "Ring", explanationMath: "Ring accent", explanationCompSci: "Character accent", usage: "\\mathring{a}" },
      { name: "overbrace", code: "\\overbrace{a+b+c}", definition: "Over brace", explanationMath: "Brace above with label", explanationCompSci: "Group annotation", usage: "\\overbrace{a+b+c}^{\\text{sum}}" },
      { name: "underbrace", code: "\\underbrace{a+b+c}", definition: "Under brace", explanationMath: "Brace below with label", explanationCompSci: "Group annotation", usage: "\\underbrace{a+b+c}_{\\text{sum}}" },
    ],
  },
  {
    title: "Big Operators",
    symbols: [
      { name: "sum", code: "\\sum_{i=1}^{n}", definition: "Summation", explanationMath: "Sum of sequence", explanationCompSci: "Loop sum; aggregate", usage: "\\sum_{i=1}^{n} x_i" },
      { name: "prod", code: "\\prod_{i=1}^{n}", definition: "Product", explanationMath: "Product of sequence", explanationCompSci: "Joint probability; product", usage: "\\prod_{i=1}^{n} i" },
      { name: "coprod", code: "\\coprod", definition: "Coproduct", explanationMath: "Disjoint union; coproduct", explanationCompSci: "Coproduct in category", usage: "\\coprod_{i}" },
      { name: "int", code: "\\int", definition: "Integral", explanationMath: "Definite/indefinite integral", explanationCompSci: "Integral; continuous sum", usage: "\\int_0^1 f(x) dx" },
      { name: "iint", code: "\\iint", definition: "Double integral", explanationMath: "Double integral", explanationCompSci: "Surface integral", usage: "\\iint_S f" },
      { name: "iiint", code: "\\iiint", definition: "Triple integral", explanationMath: "Triple integral", explanationCompSci: "Volume integral", usage: "\\iiint_V f" },
      { name: "oint", code: "\\oint", definition: "Contour integral", explanationMath: "Closed path integral", explanationCompSci: "Line integral closed", usage: "\\oint_C f" },
      { name: "oiint", code: "\\oiint", definition: "Surface integral", explanationMath: "Closed surface integral", explanationCompSci: "Flux integral", usage: "\\oiint_S" },
      { name: "oiiint", code: "\\oiiint", definition: "Volume integral", explanationMath: "Closed volume integral", explanationCompSci: "Closed volume", usage: "\\oiiint_V" },
      { name: "bigcap", code: "\\bigcap", definition: "Big intersection", explanationMath: "Intersection of family", explanationCompSci: "Set intersection", usage: "\\bigcap_{i} A_i" },
      { name: "bigcup", code: "\\bigcup", definition: "Big union", explanationMath: "Union of family", explanationCompSci: "Set union", usage: "\\bigcup_{i} A_i" },
      { name: "bigwedge", code: "\\bigwedge", definition: "Big wedge", explanationMath: "Conjunction over set", explanationCompSci: "Logical AND over set", usage: "\\bigwedge_i p_i" },
      { name: "bigvee", code: "\\bigvee", definition: "Big vee", explanationMath: "Disjunction over set", explanationCompSci: "Logical OR over set", usage: "\\bigvee_i p_i" },
      { name: "bigodot", code: "\\bigodot", definition: "Big odot", explanationMath: "Direct sum; circled dot", explanationCompSci: "Tensor product sum", usage: "\\bigodot_i" },
      { name: "bigoplus", code: "\\bigoplus", definition: "Big oplus", explanationMath: "Direct sum", explanationCompSci: "XOR; direct sum", usage: "\\bigoplus_i" },
      { name: "bigotimes", code: "\\bigotimes", definition: "Big otimes", explanationMath: "Tensor product", explanationCompSci: "Tensor product", usage: "\\bigotimes_i" },
      { name: "biguplus", code: "\\biguplus", definition: "Big uplus", explanationMath: "Disjoint union", explanationCompSci: "Disjoint union", usage: "\\biguplus_i" },
      { name: "bigsqcup", code: "\\bigsqcup", definition: "Big sqcup", explanationMath: "Disjoint union", explanationCompSci: "Disjoint union", usage: "\\bigsqcup_i" },
    ],
  },
  {
    title: "Binary Operators",
    symbols: [
      { name: "times", code: "\\times", definition: "Times", explanationMath: "Cross product; multiplication", explanationCompSci: "Cartesian product", usage: "a \\times b" },
      { name: "cdot", code: "\\cdot", definition: "Center dot", explanationMath: "Dot product; multiplication", explanationCompSci: "Dot product", usage: "a \\cdot b" },
      { name: "ast", code: "\\ast", definition: "Asterisk", explanationMath: "Convolution; multiplication", explanationCompSci: "Convolution; wildcard", usage: "a \\ast b" },
      { name: "star", code: "\\star", definition: "Star", explanationMath: "Dual; Hodge star", explanationCompSci: "Kleene star", usage: "a \\star b" },
      { name: "circ", code: "\\circ", definition: "Composition", explanationMath: "Function composition", explanationCompSci: "Composition; degree", usage: "f \\circ g" },
      { name: "bullet", code: "\\bullet", definition: "Bullet", explanationMath: "Multiplication dot", explanationCompSci: "Item marker", usage: "a \\bullet b" },
      { name: "pm", code: "\\pm", definition: "Plus minus", explanationMath: "Plus or minus", explanationCompSci: "Optional value", usage: "x \\pm 1" },
      { name: "mp", code: "\\mp", definition: "Minus plus", explanationMath: "Minus or plus", explanationCompSci: "Alternate value", usage: "x \\mp 1" },
      { name: "div", code: "\\div", definition: "Division", explanationMath: "Division", explanationCompSci: "Division operator", usage: "a \\div b" },
      { name: "cap", code: "\\cap", definition: "Intersection", explanationMath: "Set intersection", explanationCompSci: "Set intersection; meet", usage: "A \\cap B" },
      { name: "cup", code: "\\cup", definition: "Union", explanationMath: "Set union", explanationCompSci: "Set union; join", usage: "A \\cup B" },
      { name: "oplus", code: "\\oplus", definition: "XOR", explanationMath: "Direct sum; XOR", explanationCompSci: "XOR; exclusive or", usage: "a \\oplus b" },
      { name: "ominus", code: "\\ominus", definition: "Ominus", explanationMath: "Symmetric difference", explanationCompSci: "Circled minus", usage: "a \\ominus b" },
      { name: "otimes", code: "\\otimes", definition: "Tensor", explanationMath: "Tensor product", explanationCompSci: "Tensor product; Kronecker", usage: "a \\otimes b" },
      { name: "odot", code: "\\odot", definition: "Odot", explanationMath: "Hadamard product", explanationCompSci: "Element-wise product", usage: "a \\odot b" },
      { name: "oslash", code: "\\oslash", definition: "Oslash", explanationMath: "Quotient", explanationCompSci: "Circled division", usage: "a \\oslash b" },
      { name: "land", code: "\\land", definition: "Logical AND", explanationMath: "Conjunction", explanationCompSci: "AND; logical and", usage: "p \\land q" },
      { name: "lor", code: "\\lor", definition: "Logical OR", explanationMath: "Disjunction", explanationCompSci: "OR; logical or", usage: "p \\lor q" },
      { name: "vee", code: "\\vee", definition: "Wedge/Vee", explanationMath: "Join; max", explanationCompSci: "Lattice join", usage: "a \\vee b" },
      { name: "wedge", code: "\\wedge", definition: "Wedge", explanationMath: "Meet; min", explanationCompSci: "Lattice meet", usage: "a \\wedge b" },
      { name: "setminus", code: "\\setminus", definition: "Set minus", explanationMath: "Set difference", explanationCompSci: "Set difference", usage: "A \\setminus B" },
      { name: "amalg", code: "\\amalg", definition: "Amalgamation", explanationMath: "Free product", explanationCompSci: "Amalgamation", usage: "A \\amalg B" },
    ],
  },
  {
    title: "Fractions and Binomials",
    symbols: [
      { name: "frac", code: "\\frac{a}{b}", definition: "Fraction", explanationMath: "a over b", explanationCompSci: "Division; ratio", usage: "\\frac{1}{2}" },
      { name: "dfrac", code: "\\dfrac{a}{b}", definition: "Display fraction", explanationMath: "Display-style fraction", explanationCompSci: "Large fraction", usage: "\\dfrac{a}{b}" },
      { name: "tfrac", code: "\\tfrac{a}{b}", definition: "Text fraction", explanationMath: "Text-style fraction", explanationCompSci: "Small fraction", usage: "\\tfrac{a}{b}" },
      { name: "binom", code: "\\binom{n}{k}", definition: "Binomial", explanationMath: "n choose k", explanationCompSci: "Combinations; Pascal", usage: "\\binom{n}{k}" },
      { name: "dbinom", code: "\\dbinom{n}{k}", definition: "Display binomial", explanationMath: "Display binomial", explanationCompSci: "Large binomial", usage: "\\dbinom{n}{k}" },
      { name: "tbinom", code: "\\tbinom{n}{k}", definition: "Text binomial", explanationMath: "Text binomial", explanationCompSci: "Small binomial", usage: "\\tbinom{n}{k}" },
      { name: "choose", code: "{n \\choose k}", definition: "Choose (inline)", explanationMath: "n choose k", explanationCompSci: "Combinations", usage: "{n \\choose k}" },
      { name: "brace", code: "{n \\brace k}", definition: "Stirling subset", explanationMath: "Stirling numbers 2nd kind", explanationCompSci: "Partition count", usage: "{n \\brace k}" },
      { name: "brack", code: "{n \\brack k}", definition: "Stirling cycle", explanationMath: "Stirling numbers 1st kind", explanationCompSci: "Cycle count", usage: "{n \\brack k}" },
      { name: "cfrac", code: "\\cfrac{2}{1+\\cfrac{2}{1}}", definition: "Continued fraction", explanationMath: "Continued fraction", explanationCompSci: "Nested fraction", usage: "\\cfrac{a}{b+\\cfrac{c}{d}}" },
      { name: "over", code: "{a \\over b}", definition: "Over (inline)", explanationMath: "Fraction shorthand", explanationCompSci: "Division", usage: "{a \\over b}" },
    ],
  },
  {
    title: "Relations",
    symbols: [
      { name: "equals", code: "=", definition: "Equals", explanationMath: "Equality", explanationCompSci: "Assignment; equality", usage: "a = b" },
      { name: "neq", code: "\\neq", definition: "Not equal", explanationMath: "Inequality", explanationCompSci: "Not-equal comparison", usage: "a \\neq b" },
      { name: "approx", code: "\\approx", definition: "Approximately", explanationMath: "Approximate equality", explanationCompSci: "Floating-point approx", usage: "\\pi \\approx 3.14" },
      { name: "equiv", code: "\\equiv", definition: "Equivalent", explanationMath: "Congruence; equivalence", explanationCompSci: "Type equivalence", usage: "a \\equiv b \\pmod n" },
      { name: "sim", code: "\\sim", definition: "Similar", explanationMath: "Similarity; distribution", explanationCompSci: "Asymptotic", usage: "X \\sim N(0,1)" },
      { name: "simeq", code: "\\simeq", definition: "Approx equal", explanationMath: "Asymptotically equivalent", explanationCompSci: "Isomorphic approx", usage: "f \\simeq g" },
      { name: "cong", code: "\\cong", definition: "Congruent", explanationMath: "Geometric congruence", explanationCompSci: "Congruence relation", usage: "A \\cong B" },
      { name: "leq", code: "\\leq", definition: "Less or equal", explanationMath: "Less than or equal", explanationCompSci: "Comparison; bound", usage: "x \\leq 5" },
      { name: "geq", code: "\\geq", definition: "Greater or equal", explanationMath: "Greater than or equal", explanationCompSci: "Comparison; bound", usage: "x \\geq 0" },
      { name: "le", code: "\\le", definition: "Le (alias)", explanationMath: "Same as leq", explanationCompSci: "Less or equal", usage: "a \\le b" },
      { name: "ge", code: "\\ge", definition: "Ge (alias)", explanationMath: "Same as geq", explanationCompSci: "Greater or equal", usage: "a \\ge b" },
      { name: "ll", code: "\\ll", definition: "Much less", explanationMath: "Much less than", explanationCompSci: "Asymptotic", usage: "n \\ll N" },
      { name: "gg", code: "\\gg", definition: "Much greater", explanationMath: "Much greater than", explanationCompSci: "Asymptotic", usage: "n \\gg 1" },
      { name: "lt", code: "\\lt", definition: "Less than", explanationMath: "Strict less than", explanationCompSci: "Comparison", usage: "a \\lt b" },
      { name: "gt", code: "\\gt", definition: "Greater than", explanationMath: "Strict greater than", explanationCompSci: "Comparison", usage: "a \\gt b" },
      { name: "subset", code: "\\subset", definition: "Subset", explanationMath: "Proper subset", explanationCompSci: "Subset relation", usage: "A \\subset B" },
      { name: "supset", code: "\\supset", definition: "Superset", explanationMath: "Proper superset", explanationCompSci: "Superset relation", usage: "B \\supset A" },
      { name: "subseteq", code: "\\subseteq", definition: "Subset or equal", explanationMath: "Subset including equality", explanationCompSci: "Subtype", usage: "A \\subseteq B" },
      { name: "supseteq", code: "\\supseteq", definition: "Superset or equal", explanationMath: "Superset including equality", explanationCompSci: "Supertype", usage: "B \\supseteq A" },
      { name: "in", code: "\\in", definition: "Element of", explanationMath: "Set membership", explanationCompSci: "Membership; iteration", usage: "x \\in A" },
      { name: "ni", code: "\\ni", definition: "Contains", explanationMath: "Contains as element", explanationCompSci: "Reverse membership", usage: "A \\ni x" },
      { name: "notin", code: "\\notin", definition: "Not in", explanationMath: "Not element of", explanationCompSci: "Not membership", usage: "x \\notin A" },
      { name: "mid", code: "\\mid", definition: "Such that", explanationMath: "Divides; such that", explanationCompSci: "Condition; separator", usage: "\\{x \\mid x > 0\\}" },
      { name: "parallel", code: "\\parallel", definition: "Parallel", explanationMath: "Parallel lines", explanationCompSci: "Parallel relation", usage: "a \\parallel b" },
      { name: "perp", code: "\\perp", definition: "Perpendicular", explanationMath: "Perpendicular", explanationCompSci: "Orthogonal", usage: "a \\perp b" },
      { name: "propto", code: "\\propto", definition: "Proportional", explanationMath: "Proportional to", explanationCompSci: "Proportional", usage: "y \\propto x" },
      { name: "models", code: "\\models", definition: "Models", explanationMath: "Satisfies; entails", explanationCompSci: "Logical entailment", usage: "T \\models \\phi" },
      { name: "vdash", code: "\\vdash", definition: "Proves", explanationMath: "Provable; entails", explanationCompSci: "Type judgment", usage: "\\Gamma \\vdash e" },
      { name: "dashv", code: "\\dashv", definition: "Dashv", explanationMath: "Left adjoint", explanationCompSci: "Adjunction", usage: "F \\dashv G" },
    ],
  },
  {
    title: "Negated Relations",
    symbols: [
      { name: "not", code: "\\not =", definition: "Not equals", explanationMath: "Negate relation", explanationCompSci: "Negation", usage: "\\not =" },
      { name: "nless", code: "\\nless", definition: "Not less", explanationMath: "Not less than", explanationCompSci: "Negated comparison", usage: "a \\nless b" },
      { name: "ngtr", code: "\\ngtr", definition: "Not greater", explanationMath: "Not greater than", explanationCompSci: "Negated comparison", usage: "a \\ngtr b" },
      { name: "nleq", code: "\\nleq", definition: "Not leq", explanationMath: "Not less or equal", explanationCompSci: "Negated bound", usage: "a \\nleq b" },
      { name: "ngeq", code: "\\ngeq", definition: "Not geq", explanationMath: "Not greater or equal", explanationCompSci: "Negated bound", usage: "a \\ngeq b" },
      { name: "nsubseteq", code: "\\nsubseteq", definition: "Not subseteq", explanationMath: "Not subset", explanationCompSci: "Not subtype", usage: "A \\nsubseteq B" },
      { name: "nsupseteq", code: "\\nsupseteq", definition: "Not supseteq", explanationMath: "Not superset", explanationCompSci: "Not supertype", usage: "B \\nsupseteq A" },
      { name: "nmid", code: "\\nmid", definition: "Does not divide", explanationMath: "Does not divide", explanationCompSci: "Not divisor", usage: "a \\nmid b" },
      { name: "ncong", code: "\\ncong", definition: "Not congruent", explanationMath: "Not congruent", explanationCompSci: "Not congruent", usage: "A \\ncong B" },
    ],
  },
  {
    title: "Arrows",
    symbols: [
      { name: "rightarrow", code: "\\rightarrow", definition: "Right arrow", explanationMath: "Maps to; implies", explanationCompSci: "Function type; reduction", usage: "A \\rightarrow B" },
      { name: "leftarrow", code: "\\leftarrow", definition: "Left arrow", explanationMath: "Maps from", explanationCompSci: "Assignment; pullback", usage: "B \\leftarrow A" },
      { name: "leftrightarrow", code: "\\leftrightarrow", definition: "Left-right arrow", explanationMath: "Bidirectional", explanationCompSci: "Iff; bijection", usage: "A \\leftrightarrow B" },
      { name: "Rightarrow", code: "\\Rightarrow", definition: "Double right", explanationMath: "Implies; therefore", explanationCompSci: "Implication", usage: "P \\Rightarrow Q" },
      { name: "Leftarrow", code: "\\Leftarrow", definition: "Double left", explanationMath: "Implied by", explanationCompSci: "Reverse implication", usage: "Q \\Leftarrow P" },
      { name: "Leftrightarrow", code: "\\Leftrightarrow", definition: "Double iff", explanationMath: "If and only if", explanationCompSci: "Logical iff", usage: "P \\Leftrightarrow Q" },
      { name: "mapsto", code: "\\mapsto", definition: "Maps to", explanationMath: "Element mapping", explanationCompSci: "Lambda; map", usage: "x \\mapsto f(x)" },
      { name: "to", code: "\\to", definition: "To (alias)", explanationMath: "Same as rightarrow", explanationCompSci: "Function type", usage: "A \\to B" },
      { name: "gets", code: "\\gets", definition: "Gets (alias)", explanationMath: "Same as leftarrow", explanationCompSci: "Assignment", usage: "x \\gets 0" },
      { name: "implies", code: "\\implies", definition: "Implies", explanationMath: "Logical implication", explanationCompSci: "Implication", usage: "P \\implies Q" },
      { name: "impliedby", code: "\\impliedby", definition: "Implied by", explanationMath: "Reverse implication", explanationCompSci: "Converse", usage: "Q \\impliedby P" },
      { name: "iff", code: "\\iff", definition: "Iff", explanationMath: "If and only if", explanationCompSci: "Logical equivalence", usage: "P \\iff Q" },
      { name: "uparrow", code: "\\uparrow", definition: "Up arrow", explanationMath: "Increases to", explanationCompSci: "Increasing", usage: "x \\uparrow \\infty" },
      { name: "downarrow", code: "\\downarrow", definition: "Down arrow", explanationMath: "Decreases to", explanationCompSci: "Decreasing", usage: "x \\downarrow 0" },
      { name: "updownarrow", code: "\\updownarrow", definition: "Up-down", explanationMath: "Bidirectional vertical", explanationCompSci: "Vertical arrow", usage: "\\updownarrow" },
      { name: "nearrow", code: "\\nearrow", definition: "NE arrow", explanationMath: "Northeast", explanationCompSci: "Diagonal arrow", usage: "\\nearrow" },
      { name: "searrow", code: "\\searrow", definition: "SE arrow", explanationMath: "Southeast", explanationCompSci: "Diagonal arrow", usage: "\\searrow" },
      { name: "swarrow", code: "\\swarrow", definition: "SW arrow", explanationMath: "Southwest", explanationCompSci: "Diagonal arrow", usage: "\\swarrow" },
      { name: "nwarrow", code: "\\nwarrow", definition: "NW arrow", explanationMath: "Northwest", explanationCompSci: "Diagonal arrow", usage: "\\nwarrow" },
      { name: "leadsto", code: "\\leadsto", definition: "Leadsto", explanationMath: "Leads to", explanationCompSci: "Reduction", usage: "A \\leadsto B" },
    ],
  },
  {
    title: "Logic and Quantifiers",
    symbols: [
      { name: "forall", code: "\\forall", definition: "For all", explanationMath: "Universal quantifier", explanationCompSci: "Universal quantification", usage: "\\forall x \\in S" },
      { name: "exists", code: "\\exists", definition: "Exists", explanationMath: "Existential quantifier", explanationCompSci: "Existential quantification", usage: "\\exists x" },
      { name: "nexists", code: "\\nexists", definition: "Not exists", explanationMath: "There does not exist", explanationCompSci: "No witness", usage: "\\nexists x" },
      { name: "neg", code: "\\neg", definition: "Negation", explanationMath: "Logical not", explanationCompSci: "NOT; negation", usage: "\\neg p" },
      { name: "lnot", code: "\\lnot", definition: "Lnot (alias)", explanationMath: "Same as neg", explanationCompSci: "Negation", usage: "\\lnot p" },
      { name: "therefore", code: "\\therefore", definition: "Therefore", explanationMath: "Conclusion", explanationCompSci: "Therefore", usage: "P \\therefore Q" },
      { name: "because", code: "\\because", definition: "Because", explanationMath: "Premise", explanationCompSci: "Because", usage: "Q \\because P" },
      { name: "complement", code: "\\complement", definition: "Complement", explanationMath: "Set complement", explanationCompSci: "Complement set", usage: "\\complement A" },
    ],
  },
  {
    title: "Sets and Misc Symbols",
    symbols: [
      { name: "emptyset", code: "\\emptyset", definition: "Empty set", explanationMath: "Set with no elements", explanationCompSci: "Empty set; null", usage: "\\emptyset" },
      { name: "varnothing", code: "\\varnothing", definition: "Varnothing", explanationMath: "Variant empty set", explanationCompSci: "Alternative empty", usage: "\\varnothing" },
      { name: "infty", code: "\\infty", definition: "Infinity", explanationMath: "Infinity", explanationCompSci: "Unbounded; sentinel", usage: "\\lim_{x \\to \\infty}" },
      { name: "aleph", code: "\\aleph", definition: "Aleph", explanationMath: "Cardinal number", explanationCompSci: "Cardinality", usage: "\\aleph_0" },
      { name: "nabla", code: "\\nabla", definition: "Nabla", explanationMath: "Gradient; del operator", explanationCompSci: "Gradient; backprop", usage: "\\nabla f" },
      { name: "partial", code: "\\partial", definition: "Partial", explanationMath: "Partial derivative", explanationCompSci: "Partial derivative", usage: "\\frac{\\partial f}{\\partial x}" },
      { name: "prime", code: "f'", definition: "Prime", explanationMath: "Derivative; prime", explanationCompSci: "First derivative", usage: "f'(x)" },
      { name: "deg", code: "\\deg", definition: "Degree", explanationMath: "Degree of polynomial", explanationCompSci: "Degree; graph degree", usage: "\\deg f" },
      { name: "dim", code: "\\dim", definition: "Dimension", explanationMath: "Vector space dimension", explanationCompSci: "Dimension", usage: "\\dim V" },
      { name: "ker", code: "\\ker", definition: "Kernel", explanationMath: "Kernel of map", explanationCompSci: "Null space", usage: "\\ker T" },
      { name: "hom", code: "\\hom", definition: "Hom", explanationMath: "Homomorphism set", explanationCompSci: "Morphism set", usage: "\\hom(A,B)" },
      { name: "Re", code: "\\Re", definition: "Real part", explanationMath: "Real part of complex", explanationCompSci: "Real component", usage: "\\Re z" },
      { name: "Im", code: "\\Im", definition: "Imaginary part", explanationMath: "Imaginary part", explanationCompSci: "Imaginary component", usage: "\\Im z" },
      { name: "wp", code: "\\wp", definition: "Weierstrass P", explanationMath: "Weierstrass elliptic", explanationCompSci: "Power set (alternative)", usage: "\\wp" },
      { name: "ell", code: "\\ell", definition: "Curly l", explanationMath: "Avoid confusion with 1", explanationCompSci: "Length; dimension", usage: "\\ell" },
      { name: "hbar", code: "\\hbar", definition: "H-bar", explanationMath: "Planck constant over 2pi", explanationCompSci: "Quantum; reduced Planck", usage: "\\hbar" },
      { name: "N", code: "\\N", definition: "Natural numbers", explanationMath: "Natural numbers", explanationCompSci: "Natural number set", usage: "\\N" },
      { name: "Z", code: "\\Z", definition: "Integers", explanationMath: "Integers", explanationCompSci: "Integer set", usage: "\\Z" },
      { name: "R", code: "\\R", definition: "Real numbers", explanationMath: "Real numbers", explanationCompSci: "Real number set", usage: "\\R" },
      { name: "Complex", code: "\\Complex", definition: "Complex numbers", explanationMath: "Complex numbers", explanationCompSci: "Complex set", usage: "\\Complex" },
    ],
  },
  {
    title: "Delimiters",
    symbols: [
      { name: "left right", code: "\\left( x \\right)", definition: "Auto-sized parens", explanationMath: "Scale with content", explanationCompSci: "Scaled delimiters", usage: "\\left( \\frac{a}{b} \\right)" },
      { name: "big", code: "\\big(", definition: "Big delimiter", explanationMath: "1.5x size", explanationCompSci: "Scaled delimiter", usage: "\\big( \\big)" },
      { name: "Big", code: "\\Big(", definition: "Big", explanationMath: "2x size", explanationCompSci: "Larger delimiter", usage: "\\Big( \\Big)" },
      { name: "bigg", code: "\\bigg(", definition: "Bigg", explanationMath: "2.5x size", explanationCompSci: "Large delimiter", usage: "\\bigg( \\bigg)" },
      { name: "Bigg", code: "\\Bigg(", definition: "Bigg", explanationMath: "3x size", explanationCompSci: "Extra large", usage: "\\Bigg( \\Bigg)" },
      { name: "langle rangle", code: "\\langle x \\rangle", definition: "Angle brackets", explanationMath: "Inner product; expectation", explanationCompSci: "Bra-ket; inner product", usage: "\\langle x \\rangle" },
      { name: "lceil rceil", code: "\\lceil x \\rceil", definition: "Ceiling", explanationMath: "Least integer >= x", explanationCompSci: "Ceiling; up round", usage: "\\lceil x \\rceil" },
      { name: "lfloor rfloor", code: "\\lfloor x \\rfloor", definition: "Floor", explanationMath: "Greatest integer <= x", explanationCompSci: "Floor; down round", usage: "\\lfloor x \\rfloor" },
      { name: "lbrace rbrace", code: "\\lbrace \\rbrace", definition: "Braces", explanationMath: "Set notation", explanationCompSci: "Set delimiters", usage: "\\lbrace x \\rbrace" },
      { name: "lbrack rbrack", code: "\\lbrack \\rbrack", definition: "Brackets", explanationMath: "Square brackets", explanationCompSci: "Array; interval", usage: "\\lbrack a,b \\rbrack" },
      { name: "lvert rvert", code: "\\lvert x \\rvert", definition: "Absolute value", explanationMath: "Absolute value", explanationCompSci: "Abs; norm", usage: "\\lvert x \\rvert" },
      { name: "lVert rVert", code: "\\lVert x \\rVert", definition: "Norm", explanationMath: "Norm", explanationCompSci: "Vector norm", usage: "\\lVert x \\rVert" },
      { name: "middle", code: "\\middle|", definition: "Middle", explanationMath: "Scaled middle delim", explanationCompSci: "Conditional", usage: "P(A \\middle| B)" },
    ],
  },
  {
    title: "Math Functions",
    symbols: [
      { name: "sin", code: "\\sin", definition: "Sine", explanationMath: "Trigonometric sine", explanationCompSci: "Sine; activation", usage: "\\sin(x)" },
      { name: "cos", code: "\\cos", definition: "Cosine", explanationMath: "Trigonometric cosine", explanationCompSci: "Cosine; embedding", usage: "\\cos(x)" },
      { name: "tan", code: "\\tan", definition: "Tangent", explanationMath: "Trigonometric tangent", explanationCompSci: "Tangent", usage: "\\tan(x)" },
      { name: "cot", code: "\\cot", definition: "Cotangent", explanationMath: "Reciprocal of tan", explanationCompSci: "Cotangent", usage: "\\cot(x)" },
      { name: "sec", code: "\\sec", definition: "Secant", explanationMath: "Reciprocal of cos", explanationCompSci: "Secant", usage: "\\sec(x)" },
      { name: "csc", code: "\\csc", definition: "Cosecant", explanationMath: "Reciprocal of sin", explanationCompSci: "Cosecant", usage: "\\csc(x)" },
      { name: "sinh", code: "\\sinh", definition: "Hyperbolic sine", explanationMath: "Hyperbolic sine", explanationCompSci: "Sinh", usage: "\\sinh(x)" },
      { name: "cosh", code: "\\cosh", definition: "Hyperbolic cosine", explanationMath: "Hyperbolic cosine", explanationCompSci: "Cosh", usage: "\\cosh(x)" },
      { name: "tanh", code: "\\tanh", definition: "Hyperbolic tangent", explanationMath: "Hyperbolic tangent", explanationCompSci: "Tanh activation", usage: "\\tanh(x)" },
      { name: "coth", code: "\\coth", definition: "Hyperbolic cotangent", explanationMath: "Hyperbolic cot", explanationCompSci: "Coth", usage: "\\coth(x)" },
      { name: "arcsin", code: "\\arcsin", definition: "Arc sine", explanationMath: "Inverse sine", explanationCompSci: "Inverse sin", usage: "\\arcsin(x)" },
      { name: "arccos", code: "\\arccos", definition: "Arc cosine", explanationMath: "Inverse cosine", explanationCompSci: "Inverse cos", usage: "\\arccos(x)" },
      { name: "arctan", code: "\\arctan", definition: "Arc tangent", explanationMath: "Inverse tangent", explanationCompSci: "Inverse tan", usage: "\\arctan(x)" },
      { name: "log", code: "\\log", definition: "Logarithm", explanationMath: "Log (base 10 or e)", explanationCompSci: "Log; complexity", usage: "\\log x" },
      { name: "ln", code: "\\ln", definition: "Natural log", explanationMath: "Log base e", explanationCompSci: "Natural log; loss", usage: "\\ln x" },
      { name: "lg", code: "\\lg", definition: "Log base 2", explanationMath: "Binary logarithm", explanationCompSci: "Binary log", usage: "\\lg x" },
      { name: "exp", code: "\\exp", definition: "Exponential", explanationMath: "e^x", explanationCompSci: "Exponential; softmax", usage: "\\exp(x)" },
      { name: "lim", code: "\\lim", definition: "Limit", explanationMath: "Limit", explanationCompSci: "Limit; asymptotic", usage: "\\lim_{x \\to 0}" },
      { name: "liminf", code: "\\liminf", definition: "Limit inferior", explanationMath: "Limit inf", explanationCompSci: "Lim inf", usage: "\\liminf x_n" },
      { name: "limsup", code: "\\limsup", definition: "Limit superior", explanationMath: "Limit sup", explanationCompSci: "Lim sup", usage: "\\limsup x_n" },
      { name: "max", code: "\\max", definition: "Maximum", explanationMath: "Maximum", explanationCompSci: "Max; argmax", usage: "\\max_{x} f(x)" },
      { name: "min", code: "\\min", definition: "Minimum", explanationMath: "Minimum", explanationCompSci: "Min; argmin", usage: "\\min_{x} f(x)" },
      { name: "sup", code: "\\sup", definition: "Supremum", explanationMath: "Least upper bound", explanationCompSci: "Supremum", usage: "\\sup S" },
      { name: "inf", code: "\\inf", definition: "Infimum", explanationMath: "Greatest lower bound", explanationCompSci: "Infimum", usage: "\\inf S" },
      { name: "argmax", code: "\\argmax", definition: "Arg max", explanationMath: "Argument of maximum", explanationCompSci: "Argmax", usage: "\\argmax_x f(x)" },
      { name: "argmin", code: "\\argmin", definition: "Arg min", explanationMath: "Argument of minimum", explanationCompSci: "Argmin", usage: "\\argmin_x f(x)" },
      { name: "det", code: "\\det", definition: "Determinant", explanationMath: "Matrix determinant", explanationCompSci: "Determinant", usage: "\\det A" },
      { name: "gcd", code: "\\gcd", definition: "GCD", explanationMath: "Greatest common divisor", explanationCompSci: "GCD; Euclid", usage: "\\gcd(a,b)" },
      { name: "Pr", code: "\\Pr", definition: "Probability", explanationMath: "Probability", explanationCompSci: "Probability", usage: "\\Pr(X=x)" },
    ],
  },
  {
    title: "Roots and Powers",
    symbols: [
      { name: "sqrt", code: "\\sqrt{x}", definition: "Square root", explanationMath: "Principal square root", explanationCompSci: "Sqrt; distance", usage: "\\sqrt{2}" },
      { name: "sqrt[n]", code: "\\sqrt[3]{x}", definition: "Nth root", explanationMath: "Nth root", explanationCompSci: "Nth root", usage: "\\sqrt[3]{x}" },
      { name: "stackrel", code: "\\stackrel{!}{=}", definition: "Stack relation", explanationMath: "Stack symbol above", explanationCompSci: "Annotation", usage: "\\stackrel{def}{=}" },
      { name: "overset", code: "\\overset{!}{=}", definition: "Overset", explanationMath: "Put above", explanationCompSci: "Annotation", usage: "\\overset{?}{\\to}" },
      { name: "underset", code: "\\underset{n}{\\sum}", definition: "Underset", explanationMath: "Put below", explanationCompSci: "Subscript under", usage: "\\underset{x}{\\min}" },
    ],
  },
  {
    title: "Spacing and Dots",
    symbols: [
      { name: "quad", code: "\\quad", definition: "1em space", explanationMath: "Horizontal space", explanationCompSci: "Spacing", usage: "a \\quad b" },
      { name: "qquad", code: "\\qquad", definition: "2em space", explanationMath: "Double quad", explanationCompSci: "Larger spacing", usage: "a \\qquad b" },
      { name: "\\,", code: "a \\, b", definition: "Thin space", explanationMath: "Small space", explanationCompSci: "Thin space", usage: "a \\, b" },
      { name: "\\:", code: "a \\: b", definition: "Medium space", explanationMath: "Medium space", explanationCompSci: "Medium space", usage: "a \\: b" },
      { name: "\\;", code: "a \\; b", definition: "Thick space", explanationMath: "Larger space", explanationCompSci: "Thick space", usage: "a \\; b" },
      { name: "!", code: "a \\! b", definition: "Negative thin", explanationMath: "Negative thin", explanationCompSci: "Tighten", usage: "a \\! b" },
      { name: "cdots", code: "\\cdots", definition: "Center dots", explanationMath: "Horizontal ellipsis", explanationCompSci: "Continuation", usage: "x_1 + \\cdots + x_n" },
      { name: "ldots", code: "\\ldots", definition: "Low dots", explanationMath: "Baseline ellipsis", explanationCompSci: "Ellipsis", usage: "1, 2, \\ldots, n" },
      { name: "dots", code: "\\dots", definition: "Dots (auto)", explanationMath: "Smart ellipsis", explanationCompSci: "Ellipsis", usage: "\\dots" },
      { name: "vdots", code: "\\vdots", definition: "Vertical dots", explanationMath: "Vertical ellipsis", explanationCompSci: "Vertical", usage: "\\vdots" },
      { name: "ddots", code: "\\ddots", definition: "Diagonal dots", explanationMath: "Diagonal ellipsis", explanationCompSci: "Diagonal", usage: "\\ddots" },
      { name: "dotsc", code: "\\dotsc", definition: "Dots (comma)", explanationMath: "After comma", explanationCompSci: "List ellipsis", usage: "a,b,\\dotsc,z" },
      { name: "dotsb", code: "\\dotsb", definition: "Dots (binary)", explanationMath: "Between binary ops", explanationCompSci: "Sum ellipsis", usage: "a+\\dotsb+z" },
      { name: "dotsm", code: "\\dotsm", definition: "Dots (mult)", explanationMath: "Between products", explanationCompSci: "Product ellipsis", usage: "a\\dotsm z" },
    ],
  },
  {
    title: "Text and Formatting",
    symbols: [
      { name: "text", code: "\\text{hello}", definition: "Text", explanationMath: "Plain text in math", explanationCompSci: "Label; comment", usage: "\\text{hello}" },
      { name: "textbf", code: "\\textbf{bold}", definition: "Bold text", explanationMath: "Bold", explanationCompSci: "Bold", usage: "\\textbf{bold}" },
      { name: "textit", code: "\\textit{italic}", definition: "Italic text", explanationMath: "Italic", explanationCompSci: "Italic", usage: "\\textit{italic}" },
      { name: "mathrm", code: "\\mathrm{id}", definition: "Roman", explanationMath: "Upright roman", explanationCompSci: "Function name", usage: "\\mathrm{id}" },
      { name: "mathit", code: "\\mathit{var}", definition: "Italic", explanationMath: "Math italic", explanationCompSci: "Variable", usage: "\\mathit{var}" },
      { name: "mathbf", code: "\\mathbf{v}", definition: "Bold", explanationMath: "Bold math", explanationCompSci: "Vector", usage: "\\mathbf{v}" },
      { name: "mathbb", code: "\\mathbb{R}", definition: "Blackboard", explanationMath: "Number sets", explanationCompSci: "Type; set", usage: "\\mathbb{R}" },
      { name: "mathcal", code: "\\mathcal{L}", definition: "Calligraphic", explanationMath: "Lagrangian; set", explanationCompSci: "Class; lang", usage: "\\mathcal{L}" },
      { name: "mathfrak", code: "\\mathfrak{g}", definition: "Fraktur", explanationMath: "Lie algebra", explanationCompSci: "Fraktur", usage: "\\mathfrak{g}" },
      { name: "boxed", code: "\\boxed{x=5}", definition: "Boxed", explanationMath: "Highlight result", explanationCompSci: "Emphasize", usage: "\\boxed{result}" },
      { name: "cancel", code: "\\cancel{5}", definition: "Cancel", explanationMath: "Strike through", explanationCompSci: "Cancel", usage: "\\cancel{x}" },
      { name: "bcancel", code: "\\bcancel{5}", definition: "Back cancel", explanationMath: "Strike backslash", explanationCompSci: "Cancel", usage: "\\bcancel{x}" },
      { name: "xcancel", code: "\\xcancel{5}", definition: "X cancel", explanationMath: "Strike X", explanationCompSci: "Cancel", usage: "\\xcancel{x}" },
      { name: "sout", code: "\\sout{abc}", definition: "Strikethrough", explanationMath: "Strike through", explanationCompSci: "Strikethrough", usage: "\\sout{text}" },
    ],
  },
  {
    title: "Environments",
    symbols: [
      { name: "matrix", code: "\\begin{matrix}a&b\\\\c&d\\end{matrix}", definition: "Matrix (plain)", explanationMath: "Matrix no brackets", explanationCompSci: "2D array", usage: "\\begin{matrix}a&b\\\\c&d\\end{matrix}" },
      { name: "pmatrix", code: "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}", definition: "Matrix (parens)", explanationMath: "Matrix with ( )", explanationCompSci: "Matrix", usage: "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}" },
      { name: "bmatrix", code: "\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}", definition: "Matrix (brackets)", explanationMath: "Matrix with [ ]", explanationCompSci: "Matrix", usage: "\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}" },
      { name: "Bmatrix", code: "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}", definition: "Matrix (braces)", explanationMath: "Matrix with { }", explanationCompSci: "Set of vectors", usage: "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}" },
      { name: "vmatrix", code: "\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}", definition: "Matrix (determinant)", explanationMath: "Determinant bars", explanationCompSci: "Determinant", usage: "\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}" },
      { name: "Vmatrix", code: "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}", definition: "Matrix (norm)", explanationMath: "Double norm bars", explanationCompSci: "Norm matrix", usage: "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}" },
      { name: "cases", code: "\\begin{cases}a&\\text{if }b\\\\c&\\text{if }d\\end{cases}", definition: "Cases", explanationMath: "Piecewise function", explanationCompSci: "Case analysis", usage: "\\begin{cases}a&\\text{if }b\\\\c&\\text{if }d\\end{cases}" },
      { name: "array", code: "\\begin{array}{cc}a&b\\\\c&d\\end{array}", definition: "Array", explanationMath: "Tabular with alignment", explanationCompSci: "Table", usage: "\\begin{array}{cc}a&b\\\\c&d\\end{array}" },
      { name: "align", code: "\\begin{align}a&=b+c\\\\d+e&=f\\end{align}", definition: "Align", explanationMath: "Aligned equations", explanationCompSci: "Multi-line", usage: "\\begin{align}a&=b+c\\\\d+e&=f\\end{align}" },
      { name: "split", code: "\\begin{split}a&=b+c\\\\&=e+f\\end{split}", definition: "Split", explanationMath: "Split equation", explanationCompSci: "Multi-line", usage: "\\begin{split}a&=b+c\\\\&=e+f\\end{split}" },
      { name: "gather", code: "\\begin{gather}a=b\\\\e=b+c\\end{gather}", definition: "Gather", explanationMath: "Centered equations", explanationCompSci: "Stack equations", usage: "\\begin{gather}a=b\\\\e=b+c\\end{gather}" },
      { name: "smallmatrix", code: "\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}", definition: "Small matrix", explanationMath: "Inline small matrix", explanationCompSci: "Inline matrix", usage: "\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}" },
    ],
  },
  {
    title: "Misc Symbols",
    symbols: [
      { name: "angle", code: "\\angle", definition: "Angle", explanationMath: "Angle symbol", explanationCompSci: "Angle", usage: "\\angle ABC" },
      { name: "degree", code: "90^\\circ", definition: "Degree", explanationMath: "Degree symbol", explanationCompSci: "Angle degree", usage: "90^\\circ" },
      { name: "triangle", code: "\\triangle", definition: "Triangle", explanationMath: "Triangle", explanationCompSci: "Delta", usage: "\\triangle ABC" },
      { name: "square", code: "\\square", definition: "Square", explanationMath: "End of proof", explanationCompSci: "QED", usage: "\\square" },
      { name: "diamond", code: "\\diamond", definition: "Diamond", explanationMath: "Diamond", explanationCompSci: "Operator", usage: "\\diamond" },
      { name: "lozenge", code: "\\lozenge", definition: "Lozenge", explanationMath: "Diamond shape", explanationCompSci: "Modal operator", usage: "\\lozenge" },
      { name: "bullet", code: "\\bullet", definition: "Bullet", explanationMath: "Multiplication", explanationCompSci: "List item", usage: "\\bullet" },
      { name: "star", code: "\\star", definition: "Star", explanationMath: "Dual; convolution", explanationCompSci: "Kleene star", usage: "\\star" },
      { name: "bigstar", code: "\\bigstar", definition: "Big star", explanationMath: "Large star", explanationCompSci: "Emphasis", usage: "\\bigstar" },
      { name: "circ", code: "\\circ", definition: "Circle", explanationMath: "Degree; composition", explanationCompSci: "Composition", usage: "f \\circ g" },
      { name: "checkmark", code: "\\checkmark", definition: "Check", explanationMath: "Check mark", explanationCompSci: "Verified", usage: "\\checkmark" },
      { name: "dagger", code: "\\dagger", definition: "Dagger", explanationMath: "Adjoint; footnote", explanationCompSci: "Hermitian adjoint", usage: "A^\\dagger" },
      { name: "ddagger", code: "\\ddagger", definition: "Double dagger", explanationMath: "Second footnote", explanationCompSci: "Adjoint", usage: "\\ddagger" },
      { name: "copyright", code: "\\copyright", definition: "Copyright", explanationMath: "Copyright symbol", explanationCompSci: "Copyright", usage: "\\copyright" },
      { name: "pmod", code: "x \\pmod n", definition: "Pmod", explanationMath: "Parenthetical mod", explanationCompSci: "Modulo", usage: "a \\equiv b \\pmod n" },
      { name: "bmod", code: "a \\bmod b", definition: "Bmod", explanationMath: "Binary mod", explanationCompSci: "Modulo", usage: "a \\bmod b" },
    ],
  },
];
